
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: metaarivustockprooducer
          content-type: text/plain

cloud:
  aws:
    credentials:
      accessKey: 1111
      secretKey: 2222222
    region:
      static: ap-south-1
    stack:
      auto: false
